[project]
name = "alfred"
version = "0.1.0"
description = "Alfred Workflow CLI Tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pypinyin>=0.55.0",
    "pyinstaller>=6.0.0",
]

[project.scripts]
build = "scripts.build:main"

[tool.uv]
package = true
